export const API_ROUTES = {
  PRODUCTS: "/products",
  CATEGORIES: "/categories",
  CART: "/cart",
  ADD_TO_CART: "/cart/add",
  CHECKOUT: "/checkout",
  LOGIN: "/login",
  REGISTER: "/register",
  LOGOUT: "/logout",
  ME: "/me",
  STORE: "/store",
  ADMIN_STORE: "/admin/store",
  ORDERS: "/orders",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_PRODUCT_IMAGES: "/admin/product-images",
  ADMIN_CATEGORIES: "/admin/categories",
  ADMIN_COUPONS: "/admin/coupons",
  ADMIN_PAYMENTS: "/admin/payments",
  ADMIN_INVENTORY_LOGS: "/admin/inventory-logs",
  ADMIN_BRANCHES: "/admin/branches",
  ADMIN_STAFF: "/admin/staff",
  ADMIN_SALES_REPORT: "/admin/reports/sales",
  ADMIN_PROFIT_REPORT: "/admin/reports/profit",
};
